export const FICHAS = [
  // ===== THE UNFORGETTABLES (1-33) =====
  {
    name: 'Alexander',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Agitado y colado',
    garnish: 'Nuez moscada rallada',
    color: '#8B6914',
    icon: '🍫',
    ingredients: ['30ml Cognac', '30ml Crème de Cacao Marrón', '30ml Crema fresca'],
    story: 'Cóctel cremoso y elegante del siglo XIX. Originalmente hecho con ginebra, la versión con cognac se convirtió en la más popular.',
  },
  {
    name: 'Americano',
    category: 'The Unforgettables',
    glass: 'Old Fashioned (Rocks)',
    method: 'Construido',
    garnish: 'Rodaja o piel de naranja',
    color: '#B5342D',
    icon: '🇮🇹',
    ingredients: ['30ml Campari', '30ml Vermut Rojo Dulce', 'Splash de Soda'],
    story: 'Precursor del Negroni, creado en el Bar Gaspare Campari de Milán en los años 1860. Su nombre honra a los turistas americanos que lo adoraban.',
  },
  {
    name: 'Angel Face',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Agitado y colado',
    garnish: 'Sin decoración',
    color: '#E8A952',
    icon: '😇',
    ingredients: ['30ml Ginebra', '30ml Brandy de Albaricoque', '30ml Calvados'],
    story: 'Cóctel de los años 20 con proporciones iguales. Su nombre sugiere que su sabor afrutado esconde una graduación alcohólica considerable.',
  },
  {
    name: 'Aviation',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Agitado y colado',
    garnish: 'Cereza al marrasquino',
    color: '#9B8EC4',
    icon: '✈️',
    ingredients: ['45ml Ginebra', '15ml Marrasquino', '15ml Zumo de Limón', '1 barspoon Crème de Violette'],
    story: 'Creado ca. 1916, su color lila evoca el cielo. La Crème de Violette le da ese tono etéreo que recuerda a las alturas.',
  },
  {
    name: 'Between the Sheets',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Agitado y colado',
    garnish: 'Sin decoración',
    color: '#D4A84B',
    icon: '🛏️',
    ingredients: ['30ml Ron Blanco', '30ml Cognac', '30ml Triple Sec', '20ml Zumo de Limón'],
    story: 'Variación del Sidecar creada en el Harry\'s New York Bar de París en los años 30. Su nombre provocador es parte de su encanto.',
  },
  {
    name: 'Boulevardier',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Removido',
    garnish: 'Piel de naranja',
    color: '#9E2A2B',
    icon: '🎩',
    ingredients: ['45ml Bourbon o Rye Whiskey', '30ml Campari', '30ml Vermut Rojo Dulce'],
    story: 'Creado en los años 20 por Erskine Gwynne en París. Es esencialmente un Negroni con whiskey en lugar de ginebra.',
  },
  {
    name: 'Brandy Crusta',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Removido',
    garnish: 'Borde de azúcar y piel de limón',
    color: '#C4863A',
    icon: '🍋',
    ingredients: ['50.5ml Brandy', '7.5ml Marrasquino', '1 barspoon Curaçao', '15ml Zumo de Limón', '1 barspoon Jarabe Simple', '2 dash Bitters Aromáticos'],
    story: 'Creado por Joseph Santini en Nueva Orleans ca. 1850. La "crusta" de azúcar en el borde del vaso le da su nombre distintivo.',
  },
  {
    name: 'Casino',
    category: 'The Unforgettables',
    glass: 'Old Fashioned (Rocks)',
    method: 'Agitado',
    garnish: 'Cereza y piel de limón',
    color: '#D4C685',
    icon: '🎰',
    ingredients: ['40ml Old Tom Gin', '10ml Marrasquino', '10ml Zumo de Limón', '2 dash Orange Bitters'],
    story: 'Cóctel clásico que aparece en los libros de coctelería de principios del siglo XX. Su nombre evoca la elegancia de los casinos europeos.',
  },
  {
    name: 'Clover Club',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Frambuesa fresca',
    color: '#E8708A',
    icon: '🍓',
    ingredients: ['45ml Ginebra', '15ml Jarabe de Frambuesa', '15ml Zumo de Limón', 'Clara de huevo'],
    story: 'Originario del club Bellevue-Stratford de Filadelfia, anterior a la Prohibición. Su espuma rosada lo convierte en un clásico elegante.',
  },
  {
    name: 'Daiquiri',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Rodaja de lima',
    color: '#F5E6CA',
    icon: '🍹',
    ingredients: ['60ml Ron Blanco', '20ml Zumo de Lima', '2 barspoons Azúcar'],
    story: 'Nacido en las minas de Daiquirí, Cuba, en 1898. Su perfección reside en el equilibrio entre ron, ácido y dulce.',
  },
  {
    name: 'Dry Martini',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Removido',
    garnish: 'Piel de limón o aceituna',
    color: '#D5E8D4',
    icon: '🫒',
    ingredients: ['60ml Ginebra', '10ml Vermut Seco'],
    story: 'El rey de los cócteles. La proporción gin/vermut ha variado con cada era: de 2:1 en los 20s a casi solo ginebra hoy.',
  },
  {
    name: 'Gin Fizz',
    category: 'The Unforgettables',
    glass: 'Vaso Highball',
    method: 'Agitado y completado con soda',
    garnish: 'Rodaja de limón',
    color: '#E8F0D8',
    icon: '🫧',
    ingredients: ['45ml Ginebra', '30ml Zumo de Limón', '10ml Jarabe Simple', 'Soda'],
    story: 'Cóctel efervescente popular desde mediados del siglo XIX. El "fizz" hace referencia al sonido de la carbonatación al servirse.',
  },
  {
    name: 'Hanky Panky',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Removido',
    garnish: 'Piel de naranja',
    color: '#7B3F3F',
    icon: '🃏',
    ingredients: ['45ml London Dry Gin', '45ml Vermut Rojo Dulce', '7.5ml Fernet Branca'],
    story: 'Creado por Ada Coleman, bartender del Savoy Hotel de Londres, ca. 1903. Una de las primeras bartenders famosas de la historia.',
  },
  {
    name: 'John Collins',
    category: 'The Unforgettables',
    glass: 'Vaso Highball',
    method: 'Construido',
    garnish: 'Cereza y rodaja de limón',
    color: '#F5EDCB',
    icon: '🍋',
    ingredients: ['45ml Ginebra (Old Tom)', '30ml Zumo de Limón', '15ml Jarabe Simple', '60ml Soda'],
    story: 'Nombrado por un camarero del Limmer\'s Hotel de Londres en el siglo XIX. Es la base de la familia de cócteles "Collins".',
  },
  {
    name: 'Last Word',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Rodaja de lima',
    color: '#7CB342',
    icon: '🌿',
    ingredients: ['22.5ml Ginebra', '22.5ml Chartreuse Verde', '22.5ml Marrasquino', '22.5ml Zumo de Lima'],
    story: 'Creado durante la Prohibición en el Detroit Athletic Club. Redescubierto en 2004 por Murray Stenson en Seattle.',
  },
  {
    name: 'Manhattan',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Removido',
    garnish: 'Cereza al marrasquino',
    color: '#8E44AD',
    icon: '🍒',
    ingredients: ['50ml Rye Whiskey', '20ml Vermut Rojo Dulce', '1 dash Angostura Bitters'],
    story: 'Creado en el Manhattan Club de Nueva York ca. 1880. Una de las bases de la coctelería clásica americana.',
  },
  {
    name: 'Martinez',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Removido',
    garnish: 'Piel de limón',
    color: '#C49A3C',
    icon: '🥂',
    ingredients: ['45ml London Dry Gin', '45ml Vermut Rojo Dulce', '1 barspoon Marrasquino', '2 dash Orange Bitters'],
    story: 'Considerado el ancestro del Dry Martini. Aparece en los libros de coctelería de finales del siglo XIX.',
  },
  {
    name: 'Mary Pickford',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Cereza al marrasquino',
    color: '#F0A0A0',
    icon: '🎬',
    ingredients: ['45ml Ron Blanco', '45ml Zumo de Piña', '7.5ml Marrasquino', '5ml Granadina'],
    story: 'Dedicado a la estrella del cine mudo Mary Pickford durante su visita a Cuba en los años 20. Un homenaje tropical a Hollywood.',
  },
  {
    name: 'Monkey Gland',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Piel de naranja',
    color: '#E88735',
    icon: '🐒',
    ingredients: ['45ml Ginebra Seca', '45ml Zumo de Naranja', '1 cucharada Absenta', '1 cucharada Granadina'],
    story: 'Creado por Harry MacElhone en el Harry\'s Bar de París en los años 20. Su nombre viene de un tratamiento médico experimental de la época.',
  },
  {
    name: 'Negroni',
    category: 'The Unforgettables',
    glass: 'Old Fashioned (Rocks)',
    method: 'Removido',
    garnish: 'Rodaja de naranja',
    color: '#C0392B',
    icon: '🍊',
    ingredients: ['30ml Ginebra', '30ml Campari', '30ml Vermut Rojo Dulce'],
    story: 'Creado en Florencia en 1919. El Conde Negroni pidió que sustituyeran la soda de su Americano por ginebra.',
  },
  {
    name: 'Old Fashioned',
    category: 'The Unforgettables',
    glass: 'Old Fashioned (Rocks)',
    method: 'Macerado y removido',
    garnish: 'Cereza y rodaja de naranja',
    color: '#D4680A',
    icon: '🥃',
    ingredients: ['45ml Bourbon o Rye Whiskey', '1 terrón de azúcar', 'Angostura Bitters', 'Splash de agua'],
    story: 'El cóctel más antiguo conocido. La receta original era simplemente "espíritu, azúcar, agua y bitters".',
  },
  {
    name: 'Paradise',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Sin decoración',
    color: '#F4A460',
    icon: '🌴',
    ingredients: ['30ml Ginebra', '20ml Brandy de Albaricoque', '15ml Zumo de Naranja'],
    story: 'Cóctel afrutado de los años 20 que combina ginebra con brandy de albaricoque. Su nombre evoca un sabor paradisíaco.',
  },
  {
    name: "Planter's Punch",
    category: 'The Unforgettables',
    glass: 'Vaso Tumbler',
    method: 'Construido',
    garnish: 'Piel de naranja',
    color: '#CD6839',
    icon: '🏝️',
    ingredients: ['45ml Ron Jamaicano', '15ml Zumo de Lima', '30ml Zumo de Caña de Azúcar'],
    story: 'Cóctel colonial de las plantaciones del Caribe. Su receta sigue la regla: "uno de agrio, dos de dulce, tres de fuerte, cuatro de débil".',
  },
  {
    name: 'Porto Flip',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Nuez moscada rallada',
    color: '#722F37',
    icon: '🍷',
    ingredients: ['15ml Brandy', '45ml Oporto Tinto', '10ml Yema de Huevo'],
    story: 'Los "flips" eran cócteles calientes con cerveza del siglo XVII. La versión con oporto y huevo se convirtió en un clásico del siglo XIX.',
  },
  {
    name: 'Ramos Fizz',
    category: 'The Unforgettables',
    glass: 'Vaso Highball',
    method: 'Dry shake y agitado',
    garnish: 'Sin decoración',
    color: '#FAFAF0',
    icon: '☁️',
    ingredients: ['45ml Ginebra', '15ml Zumo de Lima', '15ml Zumo de Limón', '30ml Jarabe de Azúcar', '60ml Crema', '30ml Clara de Huevo', 'Agua de Azahar', 'Extracto de Vainilla', 'Soda'],
    story: 'Creado en 1888 por Henry C. Ramos en Nueva Orleans. Se necesitaban hasta 12 minutos de agitación para lograr su textura sedosa.',
  },
  {
    name: 'Rusty Nail',
    category: 'The Unforgettables',
    glass: 'Old Fashioned (Rocks)',
    method: 'Construido y removido',
    garnish: 'Piel de limón',
    color: '#B8860B',
    icon: '🔩',
    ingredients: ['45ml Scotch Whisky', '25ml Drambuie'],
    story: 'Popular en los años 60 entre la élite neoyorquina del Rat Pack. La combinación de whisky escocés y Drambuie es sencilla pero adictiva.',
  },
  {
    name: 'Sazerac',
    category: 'The Unforgettables',
    glass: 'Old Fashioned (Rocks)',
    method: 'Enjuague y removido',
    garnish: 'Piel de limón',
    color: '#DAA520',
    icon: '⚜️',
    ingredients: ['50ml Cognac o Rye Whiskey', '10ml Absenta', '1 terrón de azúcar', '4 dash Peychaud\'s Bitters'],
    story: 'Cóctel oficial de Nueva Orleans. Nació ca. 1850 en el Sazerac Coffee House con cognac Sazerac-de-Forge et Fils.',
  },
  {
    name: 'Sidecar',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Sin decoración',
    color: '#D4A017',
    icon: '🏍️',
    ingredients: ['50ml Cognac', '20ml Triple Sec', '20ml Zumo de Limón'],
    story: 'Creado en París ca. 1920s, probablemente en el Harry\'s Bar o el Ritz. Su nombre viene del sidecar de una moto.',
  },
  {
    name: 'Stinger',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Removido',
    garnish: 'Menta fresca (opcional)',
    color: '#C8B88A',
    icon: '🐝',
    ingredients: ['50ml Cognac', '20ml Crème de Menthe Blanco'],
    story: 'Cóctel digestivo favorito de la alta sociedad desde principios del siglo XX. Su "aguijón" mentolado lo hace perfecto como after-dinner.',
  },
  {
    name: 'Tuxedo',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Removido',
    garnish: 'Piel de limón y cereza',
    color: '#C5C5A0',
    icon: '🤵',
    ingredients: ['30ml Old Tom Gin', '30ml Vermut Seco', '1/2 barspoon Marrasquino', '1/4 barspoon Absenta', '3 dash Orange Bitters'],
    story: 'Nombrado por el Tuxedo Club de Nueva York, un exclusivo club de caballeros. Elegante como su nombre sugiere.',
  },
  {
    name: 'Vieux Carré',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Removido',
    garnish: 'Piel de naranja y cereza',
    color: '#8B4513',
    icon: '🎷',
    ingredients: ['30ml Rye Whiskey', '30ml Cognac', '30ml Vermut Dulce', '1 barspoon Bénédictine', '2 dash Peychaud\'s Bitters'],
    story: 'Creado en el Hotel Monteleone de Nueva Orleans en los años 30. "Vieux Carré" es el nombre francés del Barrio Francés.',
  },
  {
    name: 'Whiskey Sour',
    category: 'The Unforgettables',
    glass: 'Old Fashioned (Rocks)',
    method: 'Agitado',
    garnish: 'Rodaja de naranja y cereza',
    color: '#E67E22',
    icon: '🥃',
    ingredients: ['45ml Bourbon', '25ml Zumo de Limón', '20ml Jarabe de Azúcar', '20ml Clara de Huevo (opcional)'],
    story: 'Aparece en el libro de Jerry Thomas (1862). La clara de huevo para dar espuma es característica del estilo New York Sour.',
  },
  {
    name: 'White Lady',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Piel de limón',
    color: '#F5F5DC',
    icon: '👰',
    ingredients: ['40ml Ginebra', '30ml Triple Sec', '20ml Zumo de Limón'],
    story: 'Creado por Harry MacElhone en el Ciro\'s Club de Londres en 1919 y perfeccionado en el Harry\'s Bar de París en 1929.',
  },

  // ===== CONTEMPORARY CLASSICS (34-64) =====
  {
    name: 'Bellini',
    category: 'Contemporary Classics',
    glass: 'Flauta de Champán',
    method: 'Removido suavemente',
    garnish: 'Sin decoración',
    color: '#FADADD',
    icon: '🍑',
    ingredients: ['100ml Prosecco', '50ml Puré de Melocotón Blanco'],
    story: 'Creado por Giuseppe Cipriani en el Harry\'s Bar de Venecia en 1948. Nombrado por el pintor renacentista Giovanni Bellini.',
  },
  {
    name: 'Black Russian',
    category: 'Contemporary Classics',
    glass: 'Old Fashioned (Rocks)',
    method: 'Construido y removido',
    garnish: 'Sin decoración',
    color: '#1A0A00',
    icon: '🖤',
    ingredients: ['50ml Vodka', '20ml Licor de Café'],
    story: 'Creado en 1949 por Gustave Tops en el Hotel Metropole de Bruselas. Dedicado a la embajadora de EE.UU. Perle Mesta.',
  },
  {
    name: 'Bloody Mary',
    category: 'Contemporary Classics',
    glass: 'Vaso Highball',
    method: 'Removido',
    garnish: 'Apio y rodaja de limón',
    color: '#C0392B',
    icon: '🍅',
    ingredients: ['45ml Vodka', '90ml Zumo de Tomate', '15ml Zumo de Limón', 'Salsa Worcestershire', 'Tabasco', 'Sal de Apio', 'Pimienta'],
    story: 'Creado ca. 1921 por Fernand Petiot en el Harry\'s New York Bar de París. El "remedio para la resaca" más famoso del mundo.',
  },
  {
    name: 'Caipirinha',
    category: 'Contemporary Classics',
    glass: 'Old Fashioned (Rocks)',
    method: 'Macerado y construido',
    garnish: 'Sin decoración',
    color: '#8FBC8F',
    icon: '🇧🇷',
    ingredients: ['60ml Cachaça', '1 Lima cortada', '4 cucharaditas de Azúcar'],
    story: 'El cóctel nacional de Brasil. La cachaça, destilado de caña de azúcar, le da un carácter único y terroso.',
  },
  {
    name: 'Champagne Cocktail',
    category: 'Contemporary Classics',
    glass: 'Flauta de Champán',
    method: 'Construido',
    garnish: 'Piel de naranja y cereza',
    color: '#F9E79F',
    icon: '🍾',
    ingredients: ['90ml Champán', '10ml Cognac', '1 terrón de azúcar con Angostura'],
    story: 'Aparece en el libro de Jerry Thomas (1862). El terrón de azúcar con bitters crea un espectáculo de burbujas continuas.',
  },
  {
    name: 'Corpse Reviver #2',
    category: 'Contemporary Classics',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Piel de naranja',
    color: '#E8DAC0',
    icon: '💀',
    ingredients: ['30ml Ginebra', '30ml Cointreau', '30ml Lillet Blanc', '30ml Zumo de Limón', '1 dash Absenta'],
    story: 'Del libro "The Savoy Cocktail Book" (1930). Harry Craddock advirtió: "Toma cuatro y también serás revivido de entre los muertos".',
  },
  {
    name: 'Cosmopolitan',
    category: 'Contemporary Classics',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Twist de limón',
    color: '#E74C3C',
    icon: '🌸',
    ingredients: ['40ml Vodka Citron', '15ml Cointreau', '15ml Zumo de Lima', '30ml Zumo de Arándano'],
    story: 'Popularizado en los 90s por "Sex and the City". Creado ca. 1987-1988 por Cheryl Cook o Toby Cecchini.',
  },
  {
    name: 'Cuba Libre',
    category: 'Contemporary Classics',
    glass: 'Vaso Highball',
    method: 'Construido',
    garnish: 'Cuña de lima',
    color: '#3D1C02',
    icon: '🇨🇺',
    ingredients: ['50ml Ron Blanco', '120ml Cola', '10ml Zumo de Lima'],
    story: 'Nacido en La Habana ca. 1900 tras la independencia cubana. El grito "¡Por Cuba libre!" se convirtió en su nombre.',
  },
  {
    name: 'French 75',
    category: 'Contemporary Classics',
    glass: 'Flauta de Champán',
    method: 'Agitado y completado con champán',
    garnish: 'Sin decoración',
    color: '#ABEBC6',
    icon: '🫧',
    ingredients: ['30ml Ginebra', '15ml Zumo de Limón', '15ml Jarabe de Azúcar', '60ml Champán'],
    story: 'Creado en el New York Bar de París durante la Primera Guerra Mundial. Su nombre viene del cañón francés de 75mm por su "patada".',
  },
  {
    name: 'French Connection',
    category: 'Contemporary Classics',
    glass: 'Old Fashioned (Rocks)',
    method: 'Construido y removido',
    garnish: 'Sin decoración',
    color: '#A0522D',
    icon: '🇫🇷',
    ingredients: ['35ml Cognac', '35ml Amaretto'],
    story: 'Sencillo y elegante, combina dos licores de tradición europea. Su nombre evoca la ruta del narcotráfico franco-americana de los 70s.',
  },
  {
    name: 'Golden Dream',
    category: 'Contemporary Classics',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Sin decoración',
    color: '#FFD700',
    icon: '✨',
    ingredients: ['20ml Galliano', '20ml Triple Sec', '20ml Zumo de Naranja', '20ml Crema Fresca'],
    story: 'Un sueño dorado y cremoso, creado en los años 60. El Galliano le da su color y toque de vainilla.',
  },
  {
    name: 'Grasshopper',
    category: 'Contemporary Classics',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Sin decoración',
    color: '#3CB371',
    icon: '🦗',
    ingredients: ['20ml Crème de Cacao Blanco', '20ml Crème de Menthe Verde', '20ml Crema Fresca'],
    story: 'Cóctel postre de color verde brillante, creado en el Tujague\'s de Nueva Orleans. Popular en los años 50-60 como digestivo.',
  },
  {
    name: 'Hemingway Special',
    category: 'Contemporary Classics',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Rodaja de lima',
    color: '#FFB6C1',
    icon: '📖',
    ingredients: ['60ml Ron Blanco', '40ml Zumo de Pomelo', '15ml Marrasquino', '15ml Zumo de Lima'],
    story: 'Creado para Ernest Hemingway en el bar El Floridita de La Habana. El escritor pedía el doble de ron y sin azúcar.',
  },
  {
    name: "Horse's Neck",
    category: 'Contemporary Classics',
    glass: 'Vaso Highball',
    method: 'Construido',
    garnish: 'Espiral larga de limón',
    color: '#CDB79E',
    icon: '🐴',
    ingredients: ['40ml Cognac', '120ml Ginger Ale', '1 dash Angostura (opcional)'],
    story: 'Originalmente sin alcohol, se le añadió brandy a finales del siglo XIX. La larga espiral de limón simula el cuello de un caballo.',
  },
  {
    name: 'Irish Coffee',
    category: 'Contemporary Classics',
    glass: 'Copa de Irish Coffee',
    method: 'Construido',
    garnish: 'Sin decoración',
    color: '#3E2723',
    icon: '☕',
    ingredients: ['50ml Whiskey Irlandés', '120ml Café Caliente', '50ml Crema Batida', '1 cucharadita de Azúcar'],
    story: 'Creado por Joe Sheridan en el aeropuerto de Foynes, Irlanda, en los años 40 para calentar a los viajeros transatlánticos.',
  },
  {
    name: 'Kir',
    category: 'Contemporary Classics',
    glass: 'Copa de Vino',
    method: 'Construido',
    garnish: 'Sin decoración',
    color: '#8B0045',
    icon: '🍷',
    ingredients: ['90ml Vino Blanco Seco', '10ml Crème de Cassis'],
    story: 'Nombrado por Félix Kir, alcalde de Dijon, que lo servía en recepciones oficiales. Con champán se convierte en "Kir Royal".',
  },
  {
    name: 'Long Island Iced Tea',
    category: 'Contemporary Classics',
    glass: 'Vaso Highball',
    method: 'Construido',
    garnish: 'Rodaja de limón',
    color: '#DAA06D',
    icon: '🏖️',
    ingredients: ['15ml Vodka', '15ml Ginebra', '15ml Ron Blanco', '15ml Tequila', '15ml Triple Sec', '30ml Zumo de Limón', '20ml Jarabe', 'Cola'],
    story: 'A pesar de no llevar té, su color lo simula. Creado en los años 70 en Long Island. Famoso por su alto contenido alcohólico disimulado.',
  },
  {
    name: 'Mai Tai',
    category: 'Contemporary Classics',
    glass: 'Old Fashioned (Rocks)',
    method: 'Agitado',
    garnish: 'Piña y menta fresca',
    color: '#D2691E',
    icon: '🌺',
    ingredients: ['30ml Ron Jamaicano Ámbar', '30ml Rhum Martinica', '15ml Curaçao de Naranja', '15ml Orgeat (Jarabe de Almendra)', '30ml Zumo de Lima', '7.5ml Jarabe'],
    story: 'Creado por Trader Vic en 1944. Cuando una amiga tahitiana lo probó exclamó "Maita\'i roa ae!" (¡Muy bueno!).',
  },
  {
    name: 'Margarita',
    category: 'Contemporary Classics',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Rodaja de lima y borde de sal (opcional)',
    color: '#27AE60',
    icon: '🌵',
    ingredients: ['50ml Tequila', '20ml Triple Sec', '15ml Zumo de Lima'],
    story: 'Uno de los cócteles más pedidos del mundo. Su origen exacto es disputado entre varios bartenders de los años 40-50.',
  },
  {
    name: 'Mimosa',
    category: 'Contemporary Classics',
    glass: 'Flauta de Champán',
    method: 'Construido',
    garnish: 'Sin decoración',
    color: '#FFCC33',
    icon: '🌼',
    ingredients: ['75ml Zumo de Naranja', '75ml Prosecco'],
    story: 'Creado en el Hotel Ritz de París en 1925. Nombrado por la flor de la mimosa, por su color amarillo brillante. El clásico del brunch.',
  },
  {
    name: 'Mint Julep',
    category: 'Contemporary Classics',
    glass: 'Copa Julep (Julep Cup)',
    method: 'Macerado y construido',
    garnish: 'Ramo de menta fresca',
    color: '#2E8B57',
    icon: '🌿',
    ingredients: ['60ml Bourbon', '4 ramitas de Menta', '1 cucharadita de Azúcar', 'Agua'],
    story: 'El cóctel oficial del Kentucky Derby desde 1938. Se sirve en copa de plata o peltre para mantener el frío.',
  },
  {
    name: 'Mojito',
    category: 'Contemporary Classics',
    glass: 'Vaso Highball',
    method: 'Macerado y construido',
    garnish: 'Menta fresca y rodaja de lima',
    color: '#16A085',
    icon: '🌿',
    ingredients: ['45ml Ron Blanco', '20ml Zumo de Lima', 'Hojas de Menta', '2 cucharaditas de Azúcar', 'Soda'],
    story: 'El cóctel cubano por excelencia. Se dice que ya se bebía en La Habana en el siglo XVI, aunque con aguardiente.',
  },
  {
    name: 'Moscow Mule',
    category: 'Contemporary Classics',
    glass: 'Taza de Cobre',
    method: 'Construido',
    garnish: 'Rodaja de lima',
    color: '#BDB76B',
    icon: '🫚',
    ingredients: ['45ml Vodka', '120ml Ginger Beer', '10ml Zumo de Lima'],
    story: 'Creado en 1941 en el Cock \'n\' Bull de Hollywood para vender vodka Smirnoff. La taza de cobre es parte de su leyenda.',
  },
  {
    name: 'Piña Colada',
    category: 'Contemporary Classics',
    glass: 'Copa Huracán',
    method: 'Licuado',
    garnish: 'Piña y cereza',
    color: '#F7DC6F',
    icon: '🍍',
    ingredients: ['50ml Ron Blanco', '30ml Crema de Coco', '50ml Zumo de Piña'],
    story: 'Cóctel nacional de Puerto Rico. Creado en el Caribe Hilton de San Juan en 1954 por Ramón "Monchito" Marrero.',
  },
  {
    name: 'Pisco Sour',
    category: 'Contemporary Classics',
    glass: 'Copa Sour / Coupe',
    method: 'Agitado',
    garnish: 'Gotas de bitters en la espuma',
    color: '#F0E68C',
    icon: '🇵🇪',
    ingredients: ['60ml Pisco', '30ml Zumo de Limón', '20ml Jarabe Simple', 'Clara de Huevo', 'Bitters Angostura (decoración)'],
    story: 'Cóctel bandera de Perú (y Chile lo disputa). Creado por Victor Morris en Lima en los años 20. La espuma de clara es esencial.',
  },
  {
    name: 'Sea Breeze',
    category: 'Contemporary Classics',
    glass: 'Vaso Highball',
    method: 'Construido',
    garnish: 'Piel de naranja y cereza',
    color: '#DC3545',
    icon: '🌊',
    ingredients: ['40ml Vodka', '120ml Zumo de Arándano', '30ml Zumo de Pomelo'],
    story: 'Cóctel refrescante de los años 80 popularizado por la marca Ocean Spray. Su nombre evoca la brisa marina.',
  },
  {
    name: 'Sex on the Beach',
    category: 'Contemporary Classics',
    glass: 'Vaso Highball',
    method: 'Construido',
    garnish: 'Rodaja de naranja',
    color: '#FF6347',
    icon: '🏝️',
    ingredients: ['40ml Vodka', '20ml Licor de Melocotón (Peach Schnapps)', '40ml Zumo de Naranja', '40ml Zumo de Arándano'],
    story: 'Creado en los años 80 en Florida durante un concurso de coctelería. Su nombre provocador lo hizo inmediatamente popular.',
  },
  {
    name: 'Singapore Sling',
    category: 'Contemporary Classics',
    glass: 'Copa Huracán',
    method: 'Agitado',
    garnish: 'Piña y cereza',
    color: '#E74C3C',
    icon: '🌺',
    ingredients: ['30ml Ginebra', '15ml Cherry Heering', '7.5ml Cointreau', '7.5ml Bénédictine', '120ml Zumo de Piña', '15ml Zumo de Lima', '10ml Granadina', 'Angostura Bitters'],
    story: 'Creado ca. 1915 por Ngiam Tong Boon en el Raffles Hotel de Singapur. Receta original perdida y reconstruida.',
  },
  {
    name: 'Tequila Sunrise',
    category: 'Contemporary Classics',
    glass: 'Vaso Highball',
    method: 'Construido con granadina flotada',
    garnish: 'Rodaja de naranja',
    color: '#FF4500',
    icon: '🌅',
    ingredients: ['45ml Tequila', '90ml Zumo de Naranja', '15ml Granadina'],
    story: 'Popularizado por los Rolling Stones en su gira de 1972. El efecto degradado de colores simula un amanecer.',
  },
  {
    name: 'Vesper',
    category: 'Contemporary Classics',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Piel de limón',
    color: '#D5D5C0',
    icon: '🕵️',
    ingredients: ['45ml Ginebra', '15ml Vodka', '7.5ml Lillet Blanc'],
    story: 'Creado por Ian Fleming para James Bond en "Casino Royale" (1953). Nombrado por Vesper Lynd, la chica Bond.',
  },
  {
    name: 'Zombie',
    category: 'Contemporary Classics',
    glass: 'Vaso Tumbler Alto',
    method: 'Licuado',
    garnish: 'Ramita de menta',
    color: '#8B0000',
    icon: '🧟',
    ingredients: ['45ml Ron Jamaicano Oscuro', '45ml Ron Dorado Puertorriqueño', '30ml Ron Demerara', '20ml Zumo de Lima', '15ml Falernum', '15ml Don\'s Mix', '1 cucharadita Granadina', 'Angostura Bitters', 'Pernod'],
    story: 'Creado por Donn Beach en los años 30. Era tan fuerte que limitaba a dos por persona. Su receta fue secreta durante décadas.',
  },

  // ===== NEW ERA DRINKS (65-90) =====
  {
    name: 'Barracuda',
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Agitado y completado con prosecco',
    garnish: 'Piña y cereza',
    color: '#FFD54F',
    icon: '🐟',
    ingredients: ['45ml Ron Dorado', '15ml Galliano', '60ml Zumo de Piña', '1 dash Zumo de Lima', 'Prosecco al completar'],
    story: 'Cóctel tropical con un toque italiano del Galliano y burbujas de prosecco.',
  },
  {
    name: "Bee's Knees",
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Piel de limón o naranja',
    color: '#F0C040',
    icon: '🐝',
    ingredients: ['52.5ml Ginebra', '2 cucharaditas Jarabe de Miel', '22.5ml Zumo de Limón', '22.5ml Zumo de Naranja'],
    story: 'Cóctel de la era de la Prohibición. La miel disimulaba la ginebra de mala calidad. "Bee\'s knees" era jerga de los años 20 para "lo mejor".',
  },
  {
    name: 'Bramble',
    category: 'New Era Drinks',
    glass: 'Old Fashioned (Rocks)',
    method: 'Agitado y flotado',
    garnish: 'Rodaja de limón y moras',
    color: '#6B2D5B',
    icon: '🫐',
    ingredients: ['50ml Ginebra', '25ml Zumo de Limón', '12.5ml Jarabe de Azúcar', '15ml Crème de Mûre'],
    story: 'Creado por Dick Bradsell en Londres en 1984. Inspirado en los recuerdos de recoger moras en su infancia en la Isla de Wight.',
  },
  {
    name: 'Canchanchara',
    category: 'New Era Drinks',
    glass: 'Vaso Terracota / Rocks',
    method: 'Construido',
    garnish: 'Rodaja de lima',
    color: '#C7A252',
    icon: '🍯',
    ingredients: ['60ml Aguardiente Cubano', '15ml Zumo de Lima', '15ml Miel', '50ml Agua'],
    story: 'Bebida cubana del siglo XIX, posiblemente precursora del Daiquirí. Los soldados mambises la bebían durante las guerras de independencia.',
  },
  {
    name: "Dark 'n' Stormy",
    category: 'New Era Drinks',
    glass: 'Vaso Highball',
    method: 'Construido',
    garnish: 'Rodaja de lima',
    color: '#4A2600',
    icon: '⛈️',
    ingredients: ['60ml Ron Gosling\'s Black Seal', '100ml Ginger Beer'],
    story: 'Cóctel nacional de Bermuda. Gosling\'s tiene la marca registrada del nombre. Las "nubes oscuras" del ron flotan sobre la ginger beer.',
  },
  {
    name: 'Espresso Martini',
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Agitado fuerte',
    garnish: '3 granos de café',
    color: '#2C1810',
    icon: '☕',
    ingredients: ['50ml Vodka', '30ml Kahlúa', '10ml Jarabe de Azúcar', '1 Espresso recién hecho'],
    story: 'Creado por Dick Bradsell en 1983 en Londres. Una modelo le pidió algo que "la despertara y luego la tumbara".',
  },
  {
    name: 'Fernandito',
    category: 'New Era Drinks',
    glass: 'Vaso Highball',
    method: 'Construido con hielo',
    garnish: 'Sin decoración',
    color: '#1A1A0A',
    icon: '🇦🇷',
    ingredients: ['50ml Fernet Branca', '100ml Cola'],
    story: 'Versión argentina de Fernet con Cola, bebida nacional del país.',
  },
  {
    name: 'French Martini',
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Aceite de piel de limón',
    color: '#C24B8E',
    icon: '🍸',
    ingredients: ['45ml Vodka', '15ml Licor de Frambuesa (Chambord)', '15ml Zumo de Piña'],
    story: 'Creado en los años 80 en Nueva York. La espuma rosa y su elegancia lo hicieron favorito de los bares de moda.',
  },
  {
    name: 'Illegal',
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Sin decoración',
    color: '#A08040',
    icon: '🔥',
    ingredients: ['30ml Mezcal', '15ml Ron Overproof Jamaicano', '15ml Falernum', '1 barspoon Marrasquino', '22.5ml Zumo de Lima', '15ml Jarabe Simple', 'Clara de Huevo (opcional)'],
    story: 'Cóctel moderno que combina mezcal ahumado con ron jamaicano. Su nombre evoca lo prohibido y rebelde.',
  },
  {
    name: 'Lemon Drop',
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Borde de azúcar',
    color: '#FFF44F',
    icon: '🍬',
    ingredients: ['30ml Vodka', '20ml Triple Sec', '15ml Zumo de Limón'],
    story: 'Creado en los años 70 en San Francisco. Nombrado por el caramelo de limón, por su sabor agridulce y adictivo.',
  },
  {
    name: 'Naked and Famous',
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Sin decoración',
    color: '#D4742F',
    icon: '🌟',
    ingredients: ['22.5ml Mezcal', '22.5ml Chartreuse Amarillo', '22.5ml Aperol', '22.5ml Zumo de Lima'],
    story: 'Creado por Joaquín Simó en Death & Co. de Nueva York en 2011. Variación moderna del Last Word con mezcal.',
  },
  {
    name: 'New York Sour',
    category: 'New Era Drinks',
    glass: 'Old Fashioned (Rocks)',
    method: 'Agitado y flotado',
    garnish: 'Piel de limón/naranja y cereza',
    color: '#9B1B30',
    icon: '🗽',
    ingredients: ['60ml Rye o Bourbon', '22.5ml Jarabe de Azúcar', '30ml Zumo de Limón', 'Clara de Huevo', '15ml Vino Tinto (flotado)'],
    story: 'Un Whiskey Sour coronado con vino tinto flotante. El contraste visual de las dos capas lo hace espectacular.',
  },
  {
    name: 'Old Cuban',
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Agitado y completado con champán',
    garnish: 'Ramita de menta',
    color: '#D4B896',
    icon: '💃',
    ingredients: ['6-8 hojas de Menta', '45ml Ron Añejo', '22.5ml Zumo de Lima', '30ml Jarabe de Azúcar', '2 dash Angostura Bitters', '60ml Champán'],
    story: 'Creado por Audrey Saunders del Pegu Club de Nueva York. Un mojito elevado con champán y bitters.',
  },
  {
    name: 'Paloma',
    category: 'New Era Drinks',
    glass: 'Vaso Highball',
    method: 'Construido',
    garnish: 'Rodaja de lima',
    color: '#F5A9B8',
    icon: '🕊️',
    ingredients: ['50ml Tequila', '5ml Zumo de Lima', 'Pizca de Sal', '100ml Refresco de Pomelo Rosa'],
    story: 'El cóctel de tequila más popular en México, más que la Margarita. "Paloma" significa "paloma" en español. Sencillo y refrescante.',
  },
  {
    name: 'Paper Plane',
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Sin decoración',
    color: '#E89040',
    icon: '✈️',
    ingredients: ['30ml Bourbon', '30ml Amaro Nonino', '30ml Aperol', '30ml Zumo de Limón'],
    story: 'Creado por Sam Ross en 2007 en el Milk & Honey de Nueva York. Nombrado por la canción de M.I.A. Proporciones iguales perfectas.',
  },
  {
    name: 'Penicillin',
    category: 'New Era Drinks',
    glass: 'Old Fashioned (Rocks)',
    method: 'Macerado y agitado',
    garnish: 'Jengibre confitado',
    color: '#C4A35A',
    icon: '💊',
    ingredients: ['60ml Scotch Blended', '7.5ml Lagavulin 16', '22.5ml Zumo de Limón', '22.5ml Jarabe de Miel', 'Jengibre fresco'],
    story: 'Creado por Sam Ross en el Milk & Honey de Nueva York en 2005. El float de Lagavulin ahumado es su firma. Un clásico moderno.',
  },
  {
    name: 'Russian Spring Punch',
    category: 'New Era Drinks',
    glass: 'Vaso Highball',
    method: 'Agitado y completado con espumoso',
    garnish: 'Moras y rodaja de limón',
    color: '#7B2D8B',
    icon: '🍇',
    ingredients: ['25ml Vodka', '25ml Zumo de Limón', '15ml Crème de Cassis', '10ml Jarabe de Azúcar', 'Vino Espumoso'],
    story: 'Creado por Dick Bradsell en Londres en los años 80. Combina la frescura de un punch con la elegancia del champán.',
  },
  {
    name: 'Southside',
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Ramita de menta',
    color: '#90EE90',
    icon: '🌿',
    ingredients: ['60ml Ginebra', '30ml Zumo de Limón', '15ml Jarabe Simple', '5-6 hojas de Menta', 'Clara de Huevo (opcional)'],
    story: 'Originario del Southside Sportsmen\'s Club de Long Island. Es esencialmente un Mojito con ginebra en lugar de ron.',
  },
  {
    name: 'Spicy Fifty',
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Chile rojo',
    color: '#FF2400',
    icon: '🌶️',
    ingredients: ['50ml Vodka de Vainilla', '15ml Licor de Flor de Saúco', '15ml Zumo de Lima', '10ml Jarabe de Miel', 'Chile Rojo'],
    story: 'Creado por Salvatore Calabrese en Londres. La combinación de vainilla, flor de saúco y chile crea una experiencia de sabores contrastantes.',
  },
  {
    name: 'Spritz',
    category: 'New Era Drinks',
    glass: 'Copa de Vino',
    method: 'Construido',
    garnish: 'Rodaja de naranja',
    color: '#E8670A',
    icon: '🍊',
    ingredients: ['90ml Prosecco', '60ml Aperol', 'Splash de Soda'],
    story: 'Fenómeno global del siglo XXI. El Aperol se creó en Padua en 1919; el spritz es tradición del Véneto italiano. Receta 3-2-1.',
  },
  {
    name: 'Suffering Bastard',
    category: 'New Era Drinks',
    glass: 'Vaso Collins',
    method: 'Agitado y completado con ginger beer',
    garnish: 'Menta y rodaja de naranja',
    color: '#B8860B',
    icon: '😵',
    ingredients: ['30ml Cognac', '30ml Ginebra', '15ml Zumo de Lima', '2 dash Angostura Bitters', 'Ginger Beer'],
    story: 'Creado por Joe Scialom en el Shepheard\'s Hotel de El Cairo durante la Segunda Guerra Mundial como remedio para la resaca.',
  },
  {
    name: 'Tipperary',
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Removido',
    garnish: 'Rodaja de naranja',
    color: '#556B2F',
    icon: '🍀',
    ingredients: ['50ml Whiskey Irlandés', '25ml Vermut Dulce', '15ml Chartreuse Verde', '2 dash Angostura Bitters'],
    story: 'Nombrado por el condado irlandés de Tipperary. El Chartreuse verde le da una complejidad herbal única a este cóctel de whiskey.',
  },
  {
    name: "Tommy's Margarita",
    category: 'New Era Drinks',
    glass: 'Old Fashioned (Rocks)',
    method: 'Agitado',
    garnish: 'Rodaja de lima',
    color: '#7EC850',
    icon: '🌵',
    ingredients: ['60ml Tequila Reposado', '30ml Zumo de Lima', '30ml Néctar de Agave'],
    story: 'Creado por Julio Bermejo en Tommy\'s Mexican Restaurant de San Francisco. Sustituyó el triple sec por agave, simplificando y mejorando el clásico.',
  },
  {
    name: 'Trinidad Sour',
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Sin decoración',
    color: '#A52A2A',
    icon: '🇹🇹',
    ingredients: ['45ml Angostura Bitters', '30ml Orgeat (Jarabe de Almendra)', '22.5ml Zumo de Limón', '15ml Rye Whiskey'],
    story: 'Creado por Giuseppe González. Revolucionario por usar bitters como ingrediente principal en lugar de como acento.',
  },
  {
    name: 'Ve.N.To',
    category: 'New Era Drinks',
    glass: 'Vaso Tumbler',
    method: 'Agitado',
    garnish: 'Piel de limón y uvas',
    color: '#D4C78F',
    icon: '🍇',
    ingredients: ['45ml Grappa Blanca', '22.5ml Zumo de Limón', '15ml Mezcla de Miel y Manzanilla', '15ml Cordial de Manzanilla', '10ml Clara de Huevo (opcional)'],
    story: 'Cóctel italiano moderno que celebra la grappa del Véneto. La manzanilla le aporta un carácter floral delicado.',
  },
  {
    name: 'Yellow Bird',
    category: 'New Era Drinks',
    glass: 'Copa de Cóctel',
    method: 'Agitado',
    garnish: 'Sin decoración',
    color: '#FFD700',
    icon: '🐦',
    ingredients: ['30ml Ron Blanco', '15ml Galliano', '15ml Triple Sec', '15ml Zumo de Lima'],
    story: 'Cóctel tropical caribeño con el dulzor del Galliano y la frescura de la lima.',
  },
];

const seen = new Set();
export const fichas = FICHAS.filter(f => {
  if (seen.has(f.name)) return false;
  seen.add(f.name);
  return true;
});
