export const FICHAS = [
  {
    name: 'Negroni',
    category: 'The Unforgettables',
    glass: 'Old Fashioned (Rocks)',
    method: 'Removido',
    garnish: 'Twist o rodaja de naranja',
    color: '#c0392b',
    icon: '🍊',
    ingredients: ['3 cl Ginebra', '3 cl Campari', '3 cl Vermut Rojo'],
    story: 'Creado en Florencia en 1919. El Conde Negroni pidió que sustituyeran el soda de su Americano por ginebra. Error feliz.',
  },
  {
    name: 'Dry Martini',
    category: 'The Unforgettables',
    glass: 'Copa de Martini / Cóctel',
    method: 'Removido',
    garnish: 'Aceituna o twist de limón',
    color: '#2980b9',
    icon: '🫒',
    ingredients: ['6 cl Ginebra', '1 cl Vermut Seco'],
    story: 'El rey de los cócteles. La proporción gin/vermut ha variado con cada era: de 2:1 en los 20s a 15:1 en los 50s.',
  },
  {
    name: 'Margarita',
    category: 'Contemporary Classics',
    glass: 'Copa Margarita / Cóctel',
    method: 'Agitado',
    garnish: 'Borde de sal, rodaja de lima',
    color: '#27ae60',
    icon: '🌵',
    ingredients: ['3.5 cl Tequila Blanco', '2 cl Triple Sec / Cointreau', '1.5 cl Zumo de Lima'],
    story: 'Uno de los cócteles más pedidos del mundo. Su origen exacto es disputado entre varias barmans de los años 40-50.',
  },
  {
    name: 'Mojito',
    category: 'Contemporary Classics',
    glass: 'Vaso Highball',
    method: 'Construido / Muddled',
    garnish: 'Ramita de menta, rodaja de lima',
    color: '#16a085',
    icon: '🌿',
    ingredients: ['4.5 cl Ron Blanco', '2 cl Zumo de Lima', '1.5 cl Jarabe de Azúcar', 'Menta fresca', 'Agua con gas'],
    story: 'El cóctel cubano por excelencia. Se dice que ya se bebía en la Habana en el siglo XVI, aunque con aguardiente.',
  },
  {
    name: 'Daiquiri',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel / Coupe',
    method: 'Agitado',
    garnish: 'Twist o rodaja de lima',
    color: '#f39c12',
    icon: '🍋',
    ingredients: ['6 cl Ron Blanco', '2 cl Triple Sec', '1.5 cl Zumo de Lima'],
    story: 'Nacido en las minas de Daiquiri (Cuba, 1898). Jennings Cox y Facundo Bacardí popularizaron esta combinación refrescante.',
  },
  {
    name: 'Old Fashioned',
    category: 'The Unforgettables',
    glass: 'Old Fashioned (Rocks)',
    method: 'Removido',
    garnish: 'Twist de naranja, cereza',
    color: '#d4680a',
    icon: '🥃',
    ingredients: ['4.5 cl Bourbon o Rye Whiskey', '1 terrón de azúcar', '2 dash Angostura Bitters', 'Splash de agua'],
    story: 'El cóctel más antiguo conocido. La receta original de principios del s. XIX era simplemente "espíritu, azúcar, agua y bitters".',
  },
  {
    name: 'Manhattan',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel / Coupe',
    method: 'Removido',
    garnish: 'Cereza al marrasquino',
    color: '#8e44ad',
    icon: '🍒',
    ingredients: ['5 cl Rye Whiskey o Bourbon', '2 cl Vermut Rojo', '1 dash Angostura Bitters'],
    story: 'Creado en el Manhattan Club de Nueva York ca. 1880. Una de las bases de la coctelería clásica americana.',
  },
  {
    name: 'Cosmopolitan',
    category: 'Contemporary Classics',
    glass: 'Copa de Martini / Cóctel',
    method: 'Agitado',
    garnish: 'Twist de lima o naranja',
    color: '#e74c3c',
    icon: '🌸',
    ingredients: ['4 cl Vodka de Citrus', '1.5 cl Triple Sec', '1.5 cl Zumo de Lima', '3 cl Zumo de Arándano'],
    story: 'Popularizado en los 90s por Carrie Bradshaw en Sex and the City. Creado ca. 1987-1988 por Cheryl Cook o Toby Cecchini.',
  },
  {
    name: 'Whisky Sour',
    category: 'The Unforgettables',
    glass: 'Old Fashioned / Coupe',
    method: 'Agitado (dry shake si lleva huevo)',
    garnish: 'Rodaja de naranja, cereza',
    color: '#e67e22',
    icon: '🍊',
    ingredients: ['4.5 cl Bourbon', '3 cl Zumo de Limón', '1.5 cl Jarabe Simple', '(opcional) Clara de huevo'],
    story: 'Aparece en el libro de Jerry Thomas (1862). La adición de clara de huevo para dar espuma es característica del estilo New York.',
  },
  {
    name: 'Sazerac',
    category: 'The Unforgettables',
    glass: 'Old Fashioned (Rocks) sin hielo',
    method: 'Removido',
    garnish: 'Twist de limón (no exprimir)',
    color: '#f1c40f',
    icon: '🌿',
    ingredients: ['5 cl Rye Whiskey o Cognac', '1 terrón azúcar', '2 dash Peychaud Bitters', 'Enjuague de Absenta'],
    story: 'Cóctel oficial de Nueva Orleans. Nació ca. 1850 en el Sazerac Coffee House con cognac Sazerac-de-Forge et Fils.',
  },
  {
    name: 'Mojito',
    category: 'Contemporary Classics',
    glass: 'Vaso Highball',
    method: 'Construido / Muddled',
    garnish: 'Ramita de menta, rodaja de lima',
    color: '#16a085',
    icon: '🌿',
    ingredients: ['4.5 cl Ron Blanco', '2 cl Zumo de Lima', '1.5 cl Jarabe de Azúcar', 'Menta fresca', 'Agua con gas'],
    story: 'El cóctel cubano por excelencia. Se dice que ya se bebía en la Habana en el siglo XVI con aguardiente y hierbas.',
  },
  {
    name: 'Bloody Mary',
    category: 'Contemporary Classics',
    glass: 'Vaso Highball',
    method: 'Rodado (rolled)',
    garnish: 'Apio, aceitunas, sal de apio en el borde',
    color: '#c0392b',
    icon: '🍅',
    ingredients: ['4.5 cl Vodka', '9 cl Zumo de Tomate', '1.5 cl Zumo de Limón', 'Salsa Worcestershire', 'Tabasco', 'Sal y pimienta'],
    story: 'Creado ca. 1921-1934, atribuido a Fernand Petiot en el Harry\'s New York Bar de París. El "resaca" más famoso del mundo.',
  },
  {
    name: 'Sidecar',
    category: 'The Unforgettables',
    glass: 'Copa de Cóctel / Coupe',
    method: 'Agitado',
    garnish: 'Borde de azúcar, twist de limón',
    color: '#d4a017',
    icon: '🍋',
    ingredients: ['5 cl Cognac', '2 cl Triple Sec / Cointreau', '2 cl Zumo de Limón'],
    story: 'Creado en París ca. 1920s, probablemente en el Harry\'s Bar o el Ritz. Lleva el nombre del sidecar de una moto.',
  },
  {
    name: 'Champagne Cocktail',
    category: 'The Unforgettables',
    glass: 'Flauta de Champán',
    method: 'Construido',
    garnish: 'Twist de naranja, cereza',
    color: '#f9e79f',
    icon: '🍾',
    ingredients: ['9 cl Champán', '1 cl Cognac', '1 terrón azúcar empapado en Angostura Bitters'],
    story: 'Aparece en el libro de Jerry Thomas (1862). El terrón de azúcar empapado en bitters crea un efecto espectacular de burbujas.',
  },
  {
    name: 'Piña Colada',
    category: 'Contemporary Classics',
    glass: 'Vaso Huracán / Copa grande',
    method: 'Batido o licuado',
    garnish: 'Piña, cereza, paragüita',
    color: '#f7dc6f',
    icon: '🍍',
    ingredients: ['3 cl Ron Blanco', '3 cl Ron de Coco (o crema de coco)', '9 cl Zumo de Piña'],
    story: 'Cóctel nacional de Puerto Rico. Creado en el hotel Caribe Hilton de San Juan en 1954 por Ramón "Monchito" Marrero.',
  },
  {
    name: 'Espresso Martini',
    category: 'Contemporary Classics',
    glass: 'Copa de Martini / Cóctel',
    method: 'Agitado fuerte',
    garnish: '3 granos de café',
    color: '#2c1810',
    icon: '☕',
    ingredients: ['5 cl Vodka', '1 cl Licor de Café (Kahlúa)', '3 cl Espresso fresco'],
    story: 'Creado ca. 1983 por Dick Bradsell en el Soho Brasserie de Londres. Una modelo famosa le pidió algo que "la despertara".',
  },
  {
    name: 'Aperol Spritz',
    category: 'New Era Drinks',
    glass: 'Copa de balón grande',
    method: 'Construido',
    garnish: 'Rodaja de naranja',
    color: '#e8670a',
    icon: '🍊',
    ingredients: ['9 cl Prosecco', '6 cl Aperol', '3 cl Agua con Gas'],
    story: 'Fenómeno global del s. XXI. El Aperol se crea en Padua en 1919; el spritz es tradición del Véneto italiano. Receta 3-2-1.',
  },
  {
    name: 'French 75',
    category: 'The Unforgettables',
    glass: 'Flauta de Champán',
    method: 'Agitado + top con espumoso',
    garnish: 'Twist de limón',
    color: '#abebc6',
    icon: '🫧',
    ingredients: ['3 cl Ginebra o Cognac', '1.5 cl Zumo de Limón', '1 cl Jarabe Simple', '6 cl Champán'],
    story: 'Creado en el New York Bar de París durante la WWI. Su nombre viene del cañón francés de 75mm, por su "patada".',
  },
  {
    name: 'Moscow Mule',
    category: 'Contemporary Classics',
    glass: 'Jarra o taza de cobre',
    method: 'Construido',
    garnish: 'Rodaja de lima, jengibre confitado',
    color: '#27ae60',
    icon: '🫚',
    ingredients: ['4.5 cl Vodka', '12 cl Ginger Beer', '0.5 cl Zumo de Lima'],
    story: 'Creado en 1941 en el Cock \'n\' Bull de Hollywood para vender vodka Smirnoff. La jarra de cobre es parte de su leyenda.',
  },
  {
    name: 'Singapore Sling',
    category: 'The Unforgettables',
    glass: 'Vaso Highball',
    method: 'Agitado + top con soda',
    garnish: 'Rodaja de piña, cereza',
    color: '#e74c3c',
    icon: '🌺',
    ingredients: ['3 cl Ginebra', '1.5 cl Cherry Heering', '0.75 cl Cointreau', '0.75 cl Benedictine', '10 cl Zumo de Piña', '1.5 cl Zumo de Lima', '1 cl Granadina', 'Angostura Bitters'],
    story: 'Creado ca. 1915 por Ngiam Tong Boon en el Long Bar del Raffles Hotel de Singapur. Receta original perdida y reconstruida.',
  },
];

// Remove duplicate (Mojito appeared twice in data)
const seen = new Set();
export const fichas = FICHAS.filter(f => {
  if (seen.has(f.name)) return false;
  seen.add(f.name);
  return true;
});
