const CACHE_LIST = [
  "/",
  "/index.html",
  "/favicon.svg",
  "/logo.svg",
  "/css/style.css",
  "/trivias/all.json",
  "/trivias/general.json",
  "/trivias/historia_cocteles.json",
  "/trivias/quiensoy.json",
  "/trivias/historia_iba_fabe.json",
  "/flags/en.svg",
  "/flags/es.svg",
  // JS modules
  "/js/app.js",
  "/js/rivals.js",
  "/js/questions.js",
  "/js/learn.js",
  "/js/lang.js",
  "/js/auth.js",
  "/js/quiz.js",
  "/js/leaderboard.js",
  "/js/share.js",
  "/js/achievements.js",
  "/js/daily.js",
  "/js/speed.js",
  "/js/blind.js",
  "/js/bot.js",
  "/js/fichas.js",
  "/js/cookies.js",
  "/js/constructor.js",
  "/js/firebase-config.js",
  // i18n question bundles (contain the icon fields for Learn cards)
  "/js/i18n/questions_es.js",
  "/js/i18n/questions_en.js",
  "/js/i18n/questions_de.js",
  "/js/i18n/questions_fr.js",
  "/js/i18n/questions_pt.js"
];
const STATIC_CACHE_VERSION = `Stirio-v2.2`;
const DEBUG = false;

self.addEventListener('install', function(event) {
  if (DEBUG) {
    console.log(caches)
    console.log("SW Install Event: Is in the process");
  }
    
  const onSuccessCachesOpen = (cache) => {
    if (DEBUG) {
      console.log(cache)
      console.log("SW Install Event: Successfully opened the cache and add the cache list");
    }

    return cache.addAll(CACHE_LIST)
  }

  // Works like async/await
  event.waitUntil(
    // caches is a global variable inside the service workers file [readily available]
    caches.open(STATIC_CACHE_VERSION).then(onSuccessCachesOpen)
  )
})


self.addEventListener('activate', (event) => {
  if (DEBUG) console.log("SW Activate Event: Is in the process")

  // Google Chrome browseer -> console -> application -> cache -> cache storage
  const onSuccessCachesKeys = (cacheNames) => {
    // List of cachenames generated by STATIC_CACHE_VERSION
    if (DEBUG) console.log(cacheNames)

    // Loop through all the keys stored in cache storage
    return Promise.all(
      cacheNames.map((cache) => {
        if (cache !== STATIC_CACHE_VERSION) {
          if (DEBUG) console.log(`SW Activate Event: Remove the cache: ${cache}`);
          return caches.delete(cache)
        }
      })
    )
  }

  event.waitUntil(caches.keys().then(onSuccessCachesKeys))
})

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
})

self.addEventListener('fetch', (event) => {
  const FALLBACK_URL = CACHE_LIST[0];
  if (DEBUG) console.log("SW Fetch Event: Is in the process");

  const onSuccessFetch = response => {
    if (CACHE_LIST.includes(new URL(event.request.url).pathname)) return response

    const onSuccessDynamicCacheOpen = cache => {
      cache.put(event.request.url, response.clone())
      return response
    }

    return caches
      .open(STATIC_CACHE_VERSION)
      .then(onSuccessDynamicCacheOpen)
      .catch(() => caches.match(FALLBACK_URL))
  }

  const onErrorFetch = () => {
    const onSuccessCacheMatch = response => {
      if (response) return response
      else return caches.match(FALLBACK_URL)
    }

    return caches.match(event.request).then(onSuccessCacheMatch)
  }

  event.respondWith(
      fetch(event.request)
      .then(onSuccessFetch)
      .catch(onErrorFetch)
  )
})